### ISSUE TITLE
Afterpulses need to be disabled for (NR) simulations from G4

### ISSUE THREAD

**Issue by ramirezdiego** [XENONnT/WFSim#56]
Thanks @petergaemers for debugging! Basically, I produced an instructions file coming from the G4 output of a neutron simulation. In order to not run into problems with chunks and reverse times, entries in a single event are ordered by time where
- 1st event starts at 1us
- 2nd event starts at 1s + 1us
- 3rd event starts at 2s + 1us
- etc.

The file is located under `/dali/lgrandi/ramirezd/test_instructions_for_Peter_0.csv`. Running it with

```
st = straxen.contexts.xenonnt_simulation()
st.set_config(dict(check_raw_record_overlaps=False,
                    fax_file='test_instructions.csv'))
```

leads to errors related to one chunk endings after the next one has started, or related to the chunk ending after the chunk said it ended.

Things work nicely when running WFsim this way:
```
st.set_config(dict(check_raw_record_overlaps=False,
                   fax_file='test_instructions.csv',
                   chunk_size=30,
                   fax_config_override=dict(enable_electron_afterpulses=False,
                                           enable_pmt_afterpulses=False),))
```

but of course we lose the afterpulses (and not sure the chunk size change is not recommended).

**Comment by ramirezdiego** [comment]
Update from a second ago: things still fail under these settings. I extended the instructions up to 300 G4 events (see `/dali/lgrandi/ramirezd/test_instructions_for_Peter_1.csv`) and got this error at the end of the run:
```
Simulating Raw Records: 100%|██████████| 531/531 [16:12<00:00,  1.83s/it]
/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.6/site-packages/wfsim/strax_interface.py:271: RuntimeWarning: invalid value encountered in less_equal
  <= self.last_digitized_right * self.config['sample_duration']) |
Target Mailbox (records) killed, exception <class 'strax.mailbox.MailboxKilled'>, message (<class 'ValueError'>, ValueError('Attempt to create chunk [1.raw_records: 9223372036sec 854725808 ns - -9223372007sec 145174192 ns, 0 items, -0.0 MB/s] with negative length',), <traceback object at 0x7f819e10b208>)
Exception in thread divide_outputs:raw_records:
Traceback (most recent call last):
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.6/site-packages/strax/mailbox.py", line 262, in _send_from
    self.kill_from_exception(e)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.6/site-packages/strax/mailbox.py", line 186, in kill_from_exception
    raise e
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.6/site-packages/strax/mailbox.py", line 254, in _send_from
    x = next(iterable)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.6/site-packages/strax/plugin.py", line 379, in iter
    yield self.do_compute(chunk_i=chunk_i, **inputs_merged)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.6/site-packages/strax/plugin.py", line 459, in do_compute
    result = self.compute(**kwargs)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.6/site-packages/wfsim/strax_interface.py", line 507, in compute
    data_type=data_type) for data_type in self.provides}
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.6/site-packages/wfsim/strax_interface.py", line 507, in <dictcomp>
    data_type=data_type) for data_type in self.provides}
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.6/site-packages/strax/plugin.py", line 509, in chunk
    target_size_mb=self.chunk_target_size_mb)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.6/site-packages/strax/chunk.py", line 69, in __init__
    raise ValueError(f"Attempt to create chunk {self} "
ValueError: Attempt to create chunk [1.raw_records: 9223372036sec 854725808 ns - -9223372007sec 145174192 ns, 0 items, -0.0 MB/s] with negative length
```

**Comment by ramirezdiego** [comment]
The second error was completely my fault, sorry everyone. Let's stick to the first :)
